
[Collective]
	#When enabled, transfer the held items and armour from replaced entities by any of the Entity Spawn mods which depend on Collective.
	transferItemsBetweenReplacedEntities = true
	#Enables pets for Patrons. Will be added in a future release.
	enablePatronPets = true
	#The delay of the is-there-a-block-around-check around entities in ms. Used in mods which depends on a specific blockstate in the world. Increasing this number can increase TPS if needed.
	#Range: 0 ~ 3600000
	FindABlockcheckAroundEntitiesDelayMs = 30000

